### ISSUE TITLE
Cannot open Botic driver

### ISSUE THREAD

**Issue by gschmottlach-xse** [coroner21/botic-modules#1]
Can you comment on the issue I described here:

https://www.diyaudio.com/forums/twisted-pear/258254-support-botic-linux-driver-314.html#post6336005

Specifically, it seems all calls to actually open the Botic driver using the call
`snd_pcm_open (&capture_handle, "hw:0,0", SND_PCM_STREAM_CAPTURE, 0))` will fail with an "Invalid argument" response. Since I don't have a physical codec on the Beaglebone Black, I used the generic `snd_soc_botic_codec` codec driver. I am not sure this component is responsible for this error but I was hoping it would be adequate for my use case of capturing/playing back audio directly from the McASP0. Please advise if you have any idea what may be causing this failure or if I'm mis-understanding the application of this driver.

Thanks for making this re-factored Botic driver code available for newer kernels.

**Comment by coroner21** [comment]
Thanks, response posted in diyaudio.
